### ISSUE TITLE
Bluetooth icon

### ISSUE THREAD

**Issue by ralphee** [Anachron/i3blocks#41]
As soon as you turn off/toggle BT icon it disappears from status bar. Would be nicer in my view if the icon would be always visible in order to toggle /switch on / switch off at will. Also any chance if the BT icon could change to  or ...Thxs!

**Comment by vKnmnn** [comment]
i tried doing this for you, but since the bluetooth command is in a package i don't have, and it's not listed as dependency, this goes as untested.
help me out and do the equivalent of `pacman -Qo /usr/bin/bluetooth`
anyways, this is the untested code, you can edit your desired icon by commenting the apropriate lines in the beginning. To keep the previous behaviour, just set `OFF=""`.
```
#!/bin/bash

# ❌ 
OFF="\u274C"
#  
ON="\uf294"
#  
#ON="\uf293"
# 
#ON="\uf00c"

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  sudo bluetooth on
# Middle click
elif [[ "${BLOCK_BUTTON}" -eq 2 ]]; then
  sudo bluetooth toggle
# Right click
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
  sudo bluetooth off
fi

STATUS=$(bluetooth | grep -wo 'off\|on')
case "${STATUS}" in
    "on") 
        echo -e "$ON"
        echo -e "$ON"
        echo "" ;;
    "off")
        echo -e "$OFF"
        echo -e "$OFF"
        echo "" ;;
esac

```

**Comment by ralphee** [comment]
@vKnmnn thxs man.... `pacman -Qo /usr/lib/bluetooth' 

using systemd for all my services now
