### ISSUE TITLE
Brightness Not working

### ISSUE THREAD

**Issue by ralphee** [Anachron/i3blocks#42]
unfortunately I cant the brightness block to work or display at all in the status bar. I have xorg-xbacklight installed & xrandr. If i can provide any further detailed information pls let me know. Thxs!

http://ix.io/rSk
http://ix.io/rSo

**Comment by vKnmnn** [comment]
first of all, try running the block in a terminal, to see what it does, maybe it gives you an error message.
just navigate to the folder containing the block with your terminal and type `./brightness`. That should return a percentage value of your currently set brightness.
If there's nothing wrong here, good. But taking that the block doesn't appear in your bar means there's something wrong.
post your error message back here, so i can help you.

if all works, you can simulate the button clicking events on the block, by setting the variable before running the block like this:
`BLOCK_BUTTON=1 ./brightness` this will simulate the left mouse button, 2 is right click, 3 is middle click, 4 and 5 are scrollwheel up/down et cetera
if there's something wrong here as well, you guess it, post it back here.

if everything turns out to be working as it should, then maybe you got your config wrong. try setting the absolute path (beginning with a slash / ) in your block command.
