### ISSUE TITLE
$BLOCK_BUTTON in blocks/scroll

### ISSUE THREAD

**Issue by ghost** [Anachron/i3blocks#59]
Scrolling works pretty well but block button actions are not functioning. A click on the scrolling block does not get passed to the subscript.

**Comment by vKnmnn** [comment]
That is weird. In my understanding the Variables in the scroll script's environment should get passed to the subprocess it's invoking, right?

I will see if i can find out what's wrong. What Block are you using scroll on?

**Comment by vKnmnn** [comment]
Right, so according to Vivien's documentation, this is intended behaviour of the usage of the repeat interval.
> Note | clicks are not supported with this value, since such commands are unlikely to expect data on their standard input.

You can set the interval to 1 instead of repeat and have the block-buttons work. Obviously the scrolling effect will be much slower.

Maybe you can ask in the i3blocks-contrib [Repo](https://github.com/vivien/i3blocks-contrib) how to do work around the limitation.
